### ISSUE TITLE
LBP6020B does not work correctly!

### ISSUE THREAD

**Issue by BlackCatDevel0per** [hieplpvip/ubuntu_canon_printer#6]
Hi! I have a problem with the lbp6020b printer, after installing the driver everything works fine, but after the first reboot, the printer does not print! Or prints after reconnecting to the usb port of the printer cable, but not correctly! How can I fix this? I have ubuntu 20.04 lts

**Comment by id86** [comment]
hi i have the same problem on debian 64-bit with an lbp6000 try sudo service ccpd start, works for me at least.

**Comment by BlackCatDevel0per** [comment]
Problem solved, thanks to guys from Manjaro/Arch forums)
[#1](https://forum.manjaro.org/t/canon-6020-manjaro/28583/6)
[#2](https://archlinux.org.ru/forum/topic/20305/?page=1#post-236530)
